#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreeningONE.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ScreeningONE_Test")]
	public partial class BillingStatementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BillingStatementDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ScreeningONEConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BillingStatementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BillingStatementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BillingStatementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BillingStatementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_BillingStatement_GetCurrentStatement")]
		public ISingleResult<S1_BillingStatement_GetCurrentStatementResult> S1_BillingStatement_GetCurrentStatement([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingContactID", DbType="Int")] System.Nullable<int> billingContactID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), billingContactID, startDate, endDate);
			return ((ISingleResult<S1_BillingStatement_GetCurrentStatementResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_BillingStatement_GetBillingStatementListFromUser")]
		public ISingleResult<S1_BillingStatement_GetBillingStatementListFromUserResult> S1_BillingStatement_GetBillingStatementListFromUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, startDate, endDate);
			return ((ISingleResult<S1_BillingStatement_GetBillingStatementListFromUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_BillingStatement_GetBillingStatementListCurrentInvoices")]
		public ISingleResult<S1_BillingStatement_GetBillingStatementListCurrentInvoicesResult> S1_BillingStatement_GetBillingStatementListCurrentInvoices([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingContactID", DbType="Int")] System.Nullable<int> billingContactID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), billingContactID, startDate, endDate);
			return ((ISingleResult<S1_BillingStatement_GetBillingStatementListCurrentInvoicesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_BillingStatement_AddBillingPackagePrinted")]
		public int S1_BillingStatement_AddBillingPackagePrinted([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingContactID", DbType="Int")] System.Nullable<int> billingContactID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PackageEndDate", DbType="DateTime")] System.Nullable<System.DateTime> packageEndDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrintedByUser", DbType="Int")] System.Nullable<int> printedByUser)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), billingContactID, packageEndDate, printedByUser);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_BillingStatement_GetBillingPackagePrintedFromGUID")]
		public ISingleResult<S1_BillingStatement_GetBillingPackagePrintedFromGUIDResult> S1_BillingStatement_GetBillingPackagePrintedFromGUID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailGuid", DbType="UniqueIdentifier")] System.Nullable<System.Guid> emailGuid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), emailGuid);
			return ((ISingleResult<S1_BillingStatement_GetBillingPackagePrintedFromGUIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_BillingStatement_GetStatementEmail")]
		public ISingleResult<S1_BillingStatement_GetStatementEmailResult> S1_BillingStatement_GetStatementEmail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingContactID", DbType="Int")] System.Nullable<int> billingContactID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), billingContactID);
			return ((ISingleResult<S1_BillingStatement_GetStatementEmailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_BillingStatement_AddBillingPackagePrintedGUID")]
		public int S1_BillingStatement_AddBillingPackagePrintedGUID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingContactID", DbType="Int")] System.Nullable<int> billingContactID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PackageEndDate", DbType="DateTime")] System.Nullable<System.DateTime> packageEndDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrintedByUser", DbType="Int")] System.Nullable<int> printedByUser, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ActionGUID", DbType="VarChar(255)")] string actionGUID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), billingContactID, packageEndDate, printedByUser, actionGUID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_BillingStatement_GetSpecialPrimaryBillingContact")]
		public ISingleResult<S1_BillingStatement_GetSpecialPrimaryBillingContactResult> S1_BillingStatement_GetSpecialPrimaryBillingContact([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> billingcontactid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), billingcontactid);
			return ((ISingleResult<S1_BillingStatement_GetSpecialPrimaryBillingContactResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_BillingStatement_GetBillingStatementList")]
		public ISingleResult<S1_BillingStatement_GetBillingStatementListResult> S1_BillingStatement_GetBillingStatementList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingGroup", DbType="Int")] System.Nullable<int> billingGroup)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startDate, endDate, billingGroup);
			return ((ISingleResult<S1_BillingStatement_GetBillingStatementListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_BillingStatement_GetBillingActivity")]
		public ISingleResult<S1_BillingStatement_GetBillingActivityResult> S1_BillingStatement_GetBillingActivity([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingContactID", DbType="Int")] System.Nullable<int> billingContactID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), billingContactID, userID);
			return ((ISingleResult<S1_BillingStatement_GetBillingActivityResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_BillingStatement_GetBillingActivityForAnInvoiceIDAndPaymentID")]
		public ISingleResult<S1_BillingStatement_GetBillingActivityForAnInvoiceIDAndPaymentIDResult> S1_BillingStatement_GetBillingActivityForAnInvoiceIDAndPaymentID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingContactID", DbType="Int")] System.Nullable<int> billingContactID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InvoiceID", DbType="Int")] System.Nullable<int> invoiceID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentID", DbType="Int")] System.Nullable<int> paymentID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), billingContactID, userID, invoiceID, paymentID);
			return ((ISingleResult<S1_BillingStatement_GetBillingActivityForAnInvoiceIDAndPaymentIDResult>)(result.ReturnValue));
		}
	}
	
	public partial class S1_BillingStatement_GetCurrentStatementResult
	{
		
		private string _InvoiceNumber;
		
		private System.Nullable<System.DateTime> _Date;
		
		private string _Type;
		
		private System.Nullable<decimal> _Amount;
		
		private int _LinkID;
		
		private int _LineOrder;
		
		public S1_BillingStatement_GetCurrentStatementResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this._InvoiceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkID", DbType="Int NOT NULL")]
		public int LinkID
		{
			get
			{
				return this._LinkID;
			}
			set
			{
				if ((this._LinkID != value))
				{
					this._LinkID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineOrder", DbType="Int NOT NULL")]
		public int LineOrder
		{
			get
			{
				return this._LineOrder;
			}
			set
			{
				if ((this._LineOrder != value))
				{
					this._LineOrder = value;
				}
			}
		}
	}
	
	public partial class S1_BillingStatement_GetBillingStatementListFromUserResult
	{
		
		private int _ClientContactID;
		
		private string _ClientName;
		
		private string _ContactName;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<bool> _PrimaryBillingContact;
		
		private System.Nullable<System.DateTime> _StatementDate;
		
		private int _BillingContactID;
		
		public S1_BillingStatement_GetBillingStatementListFromUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientContactID", DbType="Int NOT NULL")]
		public int ClientContactID
		{
			get
			{
				return this._ClientContactID;
			}
			set
			{
				if ((this._ClientContactID != value))
				{
					this._ClientContactID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ClientName
		{
			get
			{
				return this._ClientName;
			}
			set
			{
				if ((this._ClientName != value))
				{
					this._ClientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="VarChar(255)")]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this._ContactName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryBillingContact", DbType="Bit")]
		public System.Nullable<bool> PrimaryBillingContact
		{
			get
			{
				return this._PrimaryBillingContact;
			}
			set
			{
				if ((this._PrimaryBillingContact != value))
				{
					this._PrimaryBillingContact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatementDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StatementDate
		{
			get
			{
				return this._StatementDate;
			}
			set
			{
				if ((this._StatementDate != value))
				{
					this._StatementDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingContactID", DbType="Int NOT NULL")]
		public int BillingContactID
		{
			get
			{
				return this._BillingContactID;
			}
			set
			{
				if ((this._BillingContactID != value))
				{
					this._BillingContactID = value;
				}
			}
		}
	}
	
	public partial class S1_BillingStatement_GetBillingStatementListCurrentInvoicesResult
	{
		
		private int _InvoiceID;
		
		private int _ClientContactID;
		
		private string _BillAsClientName;
		
		private string _ContactName;
		
		private decimal _Amount;
		
		private System.Nullable<bool> _PrimaryBillingContact;
		
		private int _BillingContactID;
		
		private string _ContactEmail;
		
		private int _DeliveryMethod;
		
		private int _CurrentActivity;
		
		public S1_BillingStatement_GetBillingStatementListCurrentInvoicesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceID", DbType="Int NOT NULL")]
		public int InvoiceID
		{
			get
			{
				return this._InvoiceID;
			}
			set
			{
				if ((this._InvoiceID != value))
				{
					this._InvoiceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientContactID", DbType="Int NOT NULL")]
		public int ClientContactID
		{
			get
			{
				return this._ClientContactID;
			}
			set
			{
				if ((this._ClientContactID != value))
				{
					this._ClientContactID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillAsClientName", DbType="VarChar(100)")]
		public string BillAsClientName
		{
			get
			{
				return this._BillAsClientName;
			}
			set
			{
				if ((this._BillAsClientName != value))
				{
					this._BillAsClientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="VarChar(255)")]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this._ContactName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryBillingContact", DbType="Bit")]
		public System.Nullable<bool> PrimaryBillingContact
		{
			get
			{
				return this._PrimaryBillingContact;
			}
			set
			{
				if ((this._PrimaryBillingContact != value))
				{
					this._PrimaryBillingContact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingContactID", DbType="Int NOT NULL")]
		public int BillingContactID
		{
			get
			{
				return this._BillingContactID;
			}
			set
			{
				if ((this._BillingContactID != value))
				{
					this._BillingContactID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactEmail", DbType="VarChar(255)")]
		public string ContactEmail
		{
			get
			{
				return this._ContactEmail;
			}
			set
			{
				if ((this._ContactEmail != value))
				{
					this._ContactEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryMethod", DbType="Int NOT NULL")]
		public int DeliveryMethod
		{
			get
			{
				return this._DeliveryMethod;
			}
			set
			{
				if ((this._DeliveryMethod != value))
				{
					this._DeliveryMethod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentActivity", DbType="Int NOT NULL")]
		public int CurrentActivity
		{
			get
			{
				return this._CurrentActivity;
			}
			set
			{
				if ((this._CurrentActivity != value))
				{
					this._CurrentActivity = value;
				}
			}
		}
	}
	
	public partial class S1_BillingStatement_GetBillingPackagePrintedFromGUIDResult
	{
		
		private int _BillingPackagePrintedID;
		
		private int _BillingContactID;
		
		private System.DateTime _PackageEndDate;
		
		private System.DateTime _PrintedOn;
		
		private int _PrintedByUser;
		
		private System.Nullable<System.Guid> _EmailGuid;
		
		public S1_BillingStatement_GetBillingPackagePrintedFromGUIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingPackagePrintedID", DbType="Int NOT NULL")]
		public int BillingPackagePrintedID
		{
			get
			{
				return this._BillingPackagePrintedID;
			}
			set
			{
				if ((this._BillingPackagePrintedID != value))
				{
					this._BillingPackagePrintedID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingContactID", DbType="Int NOT NULL")]
		public int BillingContactID
		{
			get
			{
				return this._BillingContactID;
			}
			set
			{
				if ((this._BillingContactID != value))
				{
					this._BillingContactID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageEndDate", DbType="DateTime NOT NULL")]
		public System.DateTime PackageEndDate
		{
			get
			{
				return this._PackageEndDate;
			}
			set
			{
				if ((this._PackageEndDate != value))
				{
					this._PackageEndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintedOn", DbType="DateTime NOT NULL")]
		public System.DateTime PrintedOn
		{
			get
			{
				return this._PrintedOn;
			}
			set
			{
				if ((this._PrintedOn != value))
				{
					this._PrintedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintedByUser", DbType="Int NOT NULL")]
		public int PrintedByUser
		{
			get
			{
				return this._PrintedByUser;
			}
			set
			{
				if ((this._PrintedByUser != value))
				{
					this._PrintedByUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailGuid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> EmailGuid
		{
			get
			{
				return this._EmailGuid;
			}
			set
			{
				if ((this._EmailGuid != value))
				{
					this._EmailGuid = value;
				}
			}
		}
	}
	
	public partial class S1_BillingStatement_GetStatementEmailResult
	{
		
		private string _ClientName;
		
		private string _LoweredEmail;
		
		private int _UserID;
		
		public S1_BillingStatement_GetStatementEmailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ClientName
		{
			get
			{
				return this._ClientName;
			}
			set
			{
				if ((this._ClientName != value))
				{
					this._ClientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoweredEmail", DbType="NVarChar(256)")]
		public string LoweredEmail
		{
			get
			{
				return this._LoweredEmail;
			}
			set
			{
				if ((this._LoweredEmail != value))
				{
					this._LoweredEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
	}
	
	public partial class S1_BillingStatement_GetSpecialPrimaryBillingContactResult
	{
		
		private int _BillingContactID;
		
		public S1_BillingStatement_GetSpecialPrimaryBillingContactResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingContactID", DbType="Int NOT NULL")]
		public int BillingContactID
		{
			get
			{
				return this._BillingContactID;
			}
			set
			{
				if ((this._BillingContactID != value))
				{
					this._BillingContactID = value;
				}
			}
		}
	}
	
	public partial class S1_BillingStatement_GetBillingStatementListResult
	{
		
		private int _ClientContactID;
		
		private string _BillAsClientName;
		
		private string _ContactName;
		
		private System.Nullable<decimal> _Amount;
		
		private int _PrimaryBillingContact;
		
		private System.Nullable<System.DateTime> _StatementDate;
		
		private int _BillingContactID;
		
		private string _ContactEmail;
		
		private string _DeliveryMethod;
		
		private System.Nullable<System.DateTime> _LastPrintedOn;
		
		private System.Nullable<int> _CurrentActivity;
		
		public S1_BillingStatement_GetBillingStatementListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientContactID", DbType="Int NOT NULL")]
		public int ClientContactID
		{
			get
			{
				return this._ClientContactID;
			}
			set
			{
				if ((this._ClientContactID != value))
				{
					this._ClientContactID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillAsClientName", DbType="VarChar(100)")]
		public string BillAsClientName
		{
			get
			{
				return this._BillAsClientName;
			}
			set
			{
				if ((this._BillAsClientName != value))
				{
					this._BillAsClientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="VarChar(255)")]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this._ContactName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryBillingContact", DbType="Int NOT NULL")]
		public int PrimaryBillingContact
		{
			get
			{
				return this._PrimaryBillingContact;
			}
			set
			{
				if ((this._PrimaryBillingContact != value))
				{
					this._PrimaryBillingContact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatementDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StatementDate
		{
			get
			{
				return this._StatementDate;
			}
			set
			{
				if ((this._StatementDate != value))
				{
					this._StatementDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingContactID", DbType="Int NOT NULL")]
		public int BillingContactID
		{
			get
			{
				return this._BillingContactID;
			}
			set
			{
				if ((this._BillingContactID != value))
				{
					this._BillingContactID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactEmail", DbType="VarChar(255)")]
		public string ContactEmail
		{
			get
			{
				return this._ContactEmail;
			}
			set
			{
				if ((this._ContactEmail != value))
				{
					this._ContactEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryMethod", DbType="VarChar(10)")]
		public string DeliveryMethod
		{
			get
			{
				return this._DeliveryMethod;
			}
			set
			{
				if ((this._DeliveryMethod != value))
				{
					this._DeliveryMethod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPrintedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastPrintedOn
		{
			get
			{
				return this._LastPrintedOn;
			}
			set
			{
				if ((this._LastPrintedOn != value))
				{
					this._LastPrintedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentActivity", DbType="Int")]
		public System.Nullable<int> CurrentActivity
		{
			get
			{
				return this._CurrentActivity;
			}
			set
			{
				if ((this._CurrentActivity != value))
				{
					this._CurrentActivity = value;
				}
			}
		}
	}
	
	public partial class S1_BillingStatement_GetBillingActivityResult
	{
		
		private string _InvoiceList;
		
		private string _InvoiceDateList;
		
		private string _PaymentSpentAmountList;
		
		private string _IQBTransactionIDList;
		
		private string _PtiQBTransactionIDList;
		
		private string _InvoiceNumberList;
		
		private string _PaymentList;
		
		private string _AmountReceivedList;
		
		private string _PaymentDateList;
		
		private string _PQBTransactionIDList;
		
		private string _ItpQBTransactionIDList;
		
		private System.Nullable<decimal> _TotalAmountSpent;
		
		private System.Nullable<decimal> _TotalAmountReceived;
		
		private System.Nullable<int> _InvoiceTypeID;
		
		private System.Nullable<int> _InvoiceID;
		
		private System.Nullable<int> _RelatedInvoiceID;
		
		private System.Nullable<int> _PaymentID;
		
		private System.DateTime _Date;
		
		private string _Type;
		
		private string _InvoiceNumber;
		
		private System.Nullable<decimal> _Amount;
		
		private int _LinkID;
		
		private decimal _RawAmount;
		
		private System.Nullable<bool> _HasInvoiceToInvoice;
		
		private System.Nullable<decimal> _CreditSpent;
		
		private System.Nullable<decimal> _CreditReceived;
		
		public S1_BillingStatement_GetBillingActivityResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string InvoiceList
		{
			get
			{
				return this._InvoiceList;
			}
			set
			{
				if ((this._InvoiceList != value))
				{
					this._InvoiceList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDateList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string InvoiceDateList
		{
			get
			{
				return this._InvoiceDateList;
			}
			set
			{
				if ((this._InvoiceDateList != value))
				{
					this._InvoiceDateList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentSpentAmountList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PaymentSpentAmountList
		{
			get
			{
				return this._PaymentSpentAmountList;
			}
			set
			{
				if ((this._PaymentSpentAmountList != value))
				{
					this._PaymentSpentAmountList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IQBTransactionIDList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string IQBTransactionIDList
		{
			get
			{
				return this._IQBTransactionIDList;
			}
			set
			{
				if ((this._IQBTransactionIDList != value))
				{
					this._IQBTransactionIDList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PtiQBTransactionIDList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PtiQBTransactionIDList
		{
			get
			{
				return this._PtiQBTransactionIDList;
			}
			set
			{
				if ((this._PtiQBTransactionIDList != value))
				{
					this._PtiQBTransactionIDList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumberList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string InvoiceNumberList
		{
			get
			{
				return this._InvoiceNumberList;
			}
			set
			{
				if ((this._InvoiceNumberList != value))
				{
					this._InvoiceNumberList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PaymentList
		{
			get
			{
				return this._PaymentList;
			}
			set
			{
				if ((this._PaymentList != value))
				{
					this._PaymentList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmountReceivedList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string AmountReceivedList
		{
			get
			{
				return this._AmountReceivedList;
			}
			set
			{
				if ((this._AmountReceivedList != value))
				{
					this._AmountReceivedList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentDateList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PaymentDateList
		{
			get
			{
				return this._PaymentDateList;
			}
			set
			{
				if ((this._PaymentDateList != value))
				{
					this._PaymentDateList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PQBTransactionIDList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PQBTransactionIDList
		{
			get
			{
				return this._PQBTransactionIDList;
			}
			set
			{
				if ((this._PQBTransactionIDList != value))
				{
					this._PQBTransactionIDList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItpQBTransactionIDList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ItpQBTransactionIDList
		{
			get
			{
				return this._ItpQBTransactionIDList;
			}
			set
			{
				if ((this._ItpQBTransactionIDList != value))
				{
					this._ItpQBTransactionIDList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmountSpent", DbType="Money")]
		public System.Nullable<decimal> TotalAmountSpent
		{
			get
			{
				return this._TotalAmountSpent;
			}
			set
			{
				if ((this._TotalAmountSpent != value))
				{
					this._TotalAmountSpent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmountReceived", DbType="Money")]
		public System.Nullable<decimal> TotalAmountReceived
		{
			get
			{
				return this._TotalAmountReceived;
			}
			set
			{
				if ((this._TotalAmountReceived != value))
				{
					this._TotalAmountReceived = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceTypeID", DbType="Int")]
		public System.Nullable<int> InvoiceTypeID
		{
			get
			{
				return this._InvoiceTypeID;
			}
			set
			{
				if ((this._InvoiceTypeID != value))
				{
					this._InvoiceTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceID", DbType="Int")]
		public System.Nullable<int> InvoiceID
		{
			get
			{
				return this._InvoiceID;
			}
			set
			{
				if ((this._InvoiceID != value))
				{
					this._InvoiceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedInvoiceID", DbType="Int")]
		public System.Nullable<int> RelatedInvoiceID
		{
			get
			{
				return this._RelatedInvoiceID;
			}
			set
			{
				if ((this._RelatedInvoiceID != value))
				{
					this._RelatedInvoiceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentID", DbType="Int")]
		public System.Nullable<int> PaymentID
		{
			get
			{
				return this._PaymentID;
			}
			set
			{
				if ((this._PaymentID != value))
				{
					this._PaymentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this._InvoiceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkID", DbType="Int NOT NULL")]
		public int LinkID
		{
			get
			{
				return this._LinkID;
			}
			set
			{
				if ((this._LinkID != value))
				{
					this._LinkID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RawAmount", DbType="Money NOT NULL")]
		public decimal RawAmount
		{
			get
			{
				return this._RawAmount;
			}
			set
			{
				if ((this._RawAmount != value))
				{
					this._RawAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasInvoiceToInvoice", DbType="Bit")]
		public System.Nullable<bool> HasInvoiceToInvoice
		{
			get
			{
				return this._HasInvoiceToInvoice;
			}
			set
			{
				if ((this._HasInvoiceToInvoice != value))
				{
					this._HasInvoiceToInvoice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditSpent", DbType="Money")]
		public System.Nullable<decimal> CreditSpent
		{
			get
			{
				return this._CreditSpent;
			}
			set
			{
				if ((this._CreditSpent != value))
				{
					this._CreditSpent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditReceived", DbType="Money")]
		public System.Nullable<decimal> CreditReceived
		{
			get
			{
				return this._CreditReceived;
			}
			set
			{
				if ((this._CreditReceived != value))
				{
					this._CreditReceived = value;
				}
			}
		}
	}
	
	public partial class S1_BillingStatement_GetBillingActivityForAnInvoiceIDAndPaymentIDResult
	{
		
		private string _InvoiceList;
		
		private string _InvoiceDateList;
		
		private string _PaymentSpentAmountList;
		
		private string _IQBTransactionIDList;
		
		private string _PtiQBTransactionIDList;
		
		private string _InvoiceNumberList;
		
		private string _PaymentList;
		
		private string _AmountReceivedList;
		
		private string _PaymentDateList;
		
		private string _PQBTransactionIDList;
		
		private string _ItpQBTransactionIDList;
		
		private System.Nullable<decimal> _TotalAmountSpent;
		
		private System.Nullable<decimal> _TotalAmountReceived;
		
		private System.Nullable<int> _InvoiceTypeID;
		
		private System.Nullable<int> _InvoiceID;
		
		private System.Nullable<int> _RelatedInvoiceID;
		
		private System.Nullable<int> _PaymentID;
		
		private System.DateTime _Date;
		
		private string _Type;
		
		private string _InvoiceNumber;
		
		private System.Nullable<decimal> _Amount;
		
		private int _LinkID;
		
		private decimal _RawAmount;
		
		private System.Nullable<bool> _HasInvoiceToInvoice;
		
		private System.Nullable<decimal> _CreditSpent;
		
		private System.Nullable<decimal> _CreditReceived;
		
		public S1_BillingStatement_GetBillingActivityForAnInvoiceIDAndPaymentIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string InvoiceList
		{
			get
			{
				return this._InvoiceList;
			}
			set
			{
				if ((this._InvoiceList != value))
				{
					this._InvoiceList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDateList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string InvoiceDateList
		{
			get
			{
				return this._InvoiceDateList;
			}
			set
			{
				if ((this._InvoiceDateList != value))
				{
					this._InvoiceDateList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentSpentAmountList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PaymentSpentAmountList
		{
			get
			{
				return this._PaymentSpentAmountList;
			}
			set
			{
				if ((this._PaymentSpentAmountList != value))
				{
					this._PaymentSpentAmountList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IQBTransactionIDList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string IQBTransactionIDList
		{
			get
			{
				return this._IQBTransactionIDList;
			}
			set
			{
				if ((this._IQBTransactionIDList != value))
				{
					this._IQBTransactionIDList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PtiQBTransactionIDList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PtiQBTransactionIDList
		{
			get
			{
				return this._PtiQBTransactionIDList;
			}
			set
			{
				if ((this._PtiQBTransactionIDList != value))
				{
					this._PtiQBTransactionIDList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumberList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string InvoiceNumberList
		{
			get
			{
				return this._InvoiceNumberList;
			}
			set
			{
				if ((this._InvoiceNumberList != value))
				{
					this._InvoiceNumberList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PaymentList
		{
			get
			{
				return this._PaymentList;
			}
			set
			{
				if ((this._PaymentList != value))
				{
					this._PaymentList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmountReceivedList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string AmountReceivedList
		{
			get
			{
				return this._AmountReceivedList;
			}
			set
			{
				if ((this._AmountReceivedList != value))
				{
					this._AmountReceivedList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentDateList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PaymentDateList
		{
			get
			{
				return this._PaymentDateList;
			}
			set
			{
				if ((this._PaymentDateList != value))
				{
					this._PaymentDateList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PQBTransactionIDList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PQBTransactionIDList
		{
			get
			{
				return this._PQBTransactionIDList;
			}
			set
			{
				if ((this._PQBTransactionIDList != value))
				{
					this._PQBTransactionIDList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItpQBTransactionIDList", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ItpQBTransactionIDList
		{
			get
			{
				return this._ItpQBTransactionIDList;
			}
			set
			{
				if ((this._ItpQBTransactionIDList != value))
				{
					this._ItpQBTransactionIDList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmountSpent", DbType="Money")]
		public System.Nullable<decimal> TotalAmountSpent
		{
			get
			{
				return this._TotalAmountSpent;
			}
			set
			{
				if ((this._TotalAmountSpent != value))
				{
					this._TotalAmountSpent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmountReceived", DbType="Money")]
		public System.Nullable<decimal> TotalAmountReceived
		{
			get
			{
				return this._TotalAmountReceived;
			}
			set
			{
				if ((this._TotalAmountReceived != value))
				{
					this._TotalAmountReceived = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceTypeID", DbType="Int")]
		public System.Nullable<int> InvoiceTypeID
		{
			get
			{
				return this._InvoiceTypeID;
			}
			set
			{
				if ((this._InvoiceTypeID != value))
				{
					this._InvoiceTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceID", DbType="Int")]
		public System.Nullable<int> InvoiceID
		{
			get
			{
				return this._InvoiceID;
			}
			set
			{
				if ((this._InvoiceID != value))
				{
					this._InvoiceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedInvoiceID", DbType="Int")]
		public System.Nullable<int> RelatedInvoiceID
		{
			get
			{
				return this._RelatedInvoiceID;
			}
			set
			{
				if ((this._RelatedInvoiceID != value))
				{
					this._RelatedInvoiceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentID", DbType="Int")]
		public System.Nullable<int> PaymentID
		{
			get
			{
				return this._PaymentID;
			}
			set
			{
				if ((this._PaymentID != value))
				{
					this._PaymentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this._InvoiceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkID", DbType="Int NOT NULL")]
		public int LinkID
		{
			get
			{
				return this._LinkID;
			}
			set
			{
				if ((this._LinkID != value))
				{
					this._LinkID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RawAmount", DbType="Money NOT NULL")]
		public decimal RawAmount
		{
			get
			{
				return this._RawAmount;
			}
			set
			{
				if ((this._RawAmount != value))
				{
					this._RawAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasInvoiceToInvoice", DbType="Bit")]
		public System.Nullable<bool> HasInvoiceToInvoice
		{
			get
			{
				return this._HasInvoiceToInvoice;
			}
			set
			{
				if ((this._HasInvoiceToInvoice != value))
				{
					this._HasInvoiceToInvoice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditSpent", DbType="Money")]
		public System.Nullable<decimal> CreditSpent
		{
			get
			{
				return this._CreditSpent;
			}
			set
			{
				if ((this._CreditSpent != value))
				{
					this._CreditSpent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditReceived", DbType="Money")]
		public System.Nullable<decimal> CreditReceived
		{
			get
			{
				return this._CreditReceived;
			}
			set
			{
				if ((this._CreditReceived != value))
				{
					this._CreditReceived = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
