#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreeningONE.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ScreeningONE_Test")]
	public partial class CommissionsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CommissionsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ScreeningONEConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CommissionsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CommissionsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CommissionsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CommissionsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_Commissions_PackageCommissions")]
		public ISingleResult<S1_Commissions_PackageCommissionsResult> S1_Commissions_PackageCommissions()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<S1_Commissions_PackageCommissionsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_Commissions_CreatePackageCommissions")]
		public ISingleResult<S1_Commissions_CreatePackageCommissionsResult> S1_Commissions_CreatePackageCommissions([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientID", DbType="VarChar(50)")] string clientID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientName", DbType="VarChar(500)")] string clientName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PackageName", DbType="VarChar(500)")] string packageName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PackageProducts", DbType="VarChar(800)")] string packageProducts, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PackageCommissionRate", DbType="Decimal(4,2)")] System.Nullable<decimal> packageCommissionRate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingClientID", DbType="Int")] System.Nullable<int> billingClientID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clientID, clientName, packageName, packageProducts, packageCommissionRate, billingClientID);
			return ((ISingleResult<S1_Commissions_CreatePackageCommissionsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_Commissions_RemovePackageCommissions")]
		public ISingleResult<S1_Commissions_RemovePackageCommissionsResult> S1_Commissions_RemovePackageCommissions([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PackageCommissionID", DbType="Int")] System.Nullable<int> packageCommissionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), packageCommissionID);
			return ((ISingleResult<S1_Commissions_RemovePackageCommissionsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_Commissions_UpdatePackageCommissions")]
		public ISingleResult<S1_Commissions_UpdatePackageCommissionsResult> S1_Commissions_UpdatePackageCommissions([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PackageCommissionID", DbType="Int")] System.Nullable<int> packageCommissionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientID", DbType="VarChar(50)")] string clientID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientName", DbType="VarChar(500)")] string clientName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PackageName", DbType="VarChar(500)")] string packageName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PackageProducts", DbType="VarChar(800)")] string packageProducts, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PackageCommissionRate", DbType="Decimal(4,2)")] System.Nullable<decimal> packageCommissionRate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BillingClientID", DbType="Int")] System.Nullable<int> billingClientID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), packageCommissionID, clientID, clientName, packageName, packageProducts, packageCommissionRate, billingClientID);
			return ((ISingleResult<S1_Commissions_UpdatePackageCommissionsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_Commissions_ClientsSearchByClientName")]
		public ISingleResult<S1_Commissions_ClientsSearchByClientNameResult> S1_Commissions_ClientsSearchByClientName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientName", DbType="VarChar(MAX)")] string clientName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clientName);
			return ((ISingleResult<S1_Commissions_ClientsSearchByClientNameResult>)(result.ReturnValue));
		}
	}
	
	public partial class S1_Commissions_PackageCommissionsResult
	{
		
		private int _PackageCommissionID;
		
		private string _ClientID;
		
		private string _ClientName;
		
		private string _PackageName;
		
		private string _PackageProducts;
		
		private decimal _PackageCommissionRate;
		
		private System.Nullable<int> _BillingClientID;
		
		public S1_Commissions_PackageCommissionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageCommissionID", DbType="Int NOT NULL")]
		public int PackageCommissionID
		{
			get
			{
				return this._PackageCommissionID;
			}
			set
			{
				if ((this._PackageCommissionID != value))
				{
					this._PackageCommissionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this._ClientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientName", DbType="VarChar(500)")]
		public string ClientName
		{
			get
			{
				return this._ClientName;
			}
			set
			{
				if ((this._ClientName != value))
				{
					this._ClientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageName", DbType="VarChar(500)")]
		public string PackageName
		{
			get
			{
				return this._PackageName;
			}
			set
			{
				if ((this._PackageName != value))
				{
					this._PackageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageProducts", DbType="VarChar(800)")]
		public string PackageProducts
		{
			get
			{
				return this._PackageProducts;
			}
			set
			{
				if ((this._PackageProducts != value))
				{
					this._PackageProducts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageCommissionRate", DbType="Decimal(4,2) NOT NULL")]
		public decimal PackageCommissionRate
		{
			get
			{
				return this._PackageCommissionRate;
			}
			set
			{
				if ((this._PackageCommissionRate != value))
				{
					this._PackageCommissionRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingClientID", DbType="Int")]
		public System.Nullable<int> BillingClientID
		{
			get
			{
				return this._BillingClientID;
			}
			set
			{
				if ((this._BillingClientID != value))
				{
					this._BillingClientID = value;
				}
			}
		}
	}
	
	public partial class S1_Commissions_CreatePackageCommissionsResult
	{
		
		private int _PackageCommissionID;
		
		private string _ClientID;
		
		private string _ClientName;
		
		private string _PackageName;
		
		private string _PackageProducts;
		
		private decimal _PackageCommissionRate;
		
		private System.Nullable<int> _BillingClientID;
		
		public S1_Commissions_CreatePackageCommissionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageCommissionID", DbType="Int NOT NULL")]
		public int PackageCommissionID
		{
			get
			{
				return this._PackageCommissionID;
			}
			set
			{
				if ((this._PackageCommissionID != value))
				{
					this._PackageCommissionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this._ClientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientName", DbType="VarChar(500)")]
		public string ClientName
		{
			get
			{
				return this._ClientName;
			}
			set
			{
				if ((this._ClientName != value))
				{
					this._ClientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageName", DbType="VarChar(500)")]
		public string PackageName
		{
			get
			{
				return this._PackageName;
			}
			set
			{
				if ((this._PackageName != value))
				{
					this._PackageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageProducts", DbType="VarChar(800)")]
		public string PackageProducts
		{
			get
			{
				return this._PackageProducts;
			}
			set
			{
				if ((this._PackageProducts != value))
				{
					this._PackageProducts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageCommissionRate", DbType="Decimal(4,2) NOT NULL")]
		public decimal PackageCommissionRate
		{
			get
			{
				return this._PackageCommissionRate;
			}
			set
			{
				if ((this._PackageCommissionRate != value))
				{
					this._PackageCommissionRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingClientID", DbType="Int")]
		public System.Nullable<int> BillingClientID
		{
			get
			{
				return this._BillingClientID;
			}
			set
			{
				if ((this._BillingClientID != value))
				{
					this._BillingClientID = value;
				}
			}
		}
	}
	
	public partial class S1_Commissions_RemovePackageCommissionsResult
	{
		
		private int _PackageCommissionID;
		
		private string _ClientID;
		
		private string _ClientName;
		
		private string _PackageName;
		
		private string _PackageProducts;
		
		private decimal _PackageCommissionRate;
		
		private System.Nullable<int> _BillingClientID;
		
		public S1_Commissions_RemovePackageCommissionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageCommissionID", DbType="Int NOT NULL")]
		public int PackageCommissionID
		{
			get
			{
				return this._PackageCommissionID;
			}
			set
			{
				if ((this._PackageCommissionID != value))
				{
					this._PackageCommissionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this._ClientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientName", DbType="VarChar(500)")]
		public string ClientName
		{
			get
			{
				return this._ClientName;
			}
			set
			{
				if ((this._ClientName != value))
				{
					this._ClientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageName", DbType="VarChar(500)")]
		public string PackageName
		{
			get
			{
				return this._PackageName;
			}
			set
			{
				if ((this._PackageName != value))
				{
					this._PackageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageProducts", DbType="VarChar(800)")]
		public string PackageProducts
		{
			get
			{
				return this._PackageProducts;
			}
			set
			{
				if ((this._PackageProducts != value))
				{
					this._PackageProducts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageCommissionRate", DbType="Decimal(4,2) NOT NULL")]
		public decimal PackageCommissionRate
		{
			get
			{
				return this._PackageCommissionRate;
			}
			set
			{
				if ((this._PackageCommissionRate != value))
				{
					this._PackageCommissionRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingClientID", DbType="Int")]
		public System.Nullable<int> BillingClientID
		{
			get
			{
				return this._BillingClientID;
			}
			set
			{
				if ((this._BillingClientID != value))
				{
					this._BillingClientID = value;
				}
			}
		}
	}
	
	public partial class S1_Commissions_UpdatePackageCommissionsResult
	{
		
		private int _PackageCommissionID;
		
		private string _ClientID;
		
		private string _ClientName;
		
		private string _PackageName;
		
		private string _PackageProducts;
		
		private decimal _PackageCommissionRate;
		
		private System.Nullable<int> _BillingClientID;
		
		public S1_Commissions_UpdatePackageCommissionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageCommissionID", DbType="Int NOT NULL")]
		public int PackageCommissionID
		{
			get
			{
				return this._PackageCommissionID;
			}
			set
			{
				if ((this._PackageCommissionID != value))
				{
					this._PackageCommissionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this._ClientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientName", DbType="VarChar(500)")]
		public string ClientName
		{
			get
			{
				return this._ClientName;
			}
			set
			{
				if ((this._ClientName != value))
				{
					this._ClientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageName", DbType="VarChar(500)")]
		public string PackageName
		{
			get
			{
				return this._PackageName;
			}
			set
			{
				if ((this._PackageName != value))
				{
					this._PackageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageProducts", DbType="VarChar(800)")]
		public string PackageProducts
		{
			get
			{
				return this._PackageProducts;
			}
			set
			{
				if ((this._PackageProducts != value))
				{
					this._PackageProducts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageCommissionRate", DbType="Decimal(4,2) NOT NULL")]
		public decimal PackageCommissionRate
		{
			get
			{
				return this._PackageCommissionRate;
			}
			set
			{
				if ((this._PackageCommissionRate != value))
				{
					this._PackageCommissionRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingClientID", DbType="Int")]
		public System.Nullable<int> BillingClientID
		{
			get
			{
				return this._BillingClientID;
			}
			set
			{
				if ((this._BillingClientID != value))
				{
					this._BillingClientID = value;
				}
			}
		}
	}
	
	public partial class S1_Commissions_ClientsSearchByClientNameResult
	{
		
		private System.Nullable<int> _ParentBillingClientID;
		
		private int _BillingClientID;
		
		private string _ClientName;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _City;
		
		private string _State;
		
		private string _ZipCode;
		
		private System.Nullable<bool> _DoNotInvoice;
		
		private System.Nullable<bool> _GetsInvoiceDetail;
		
		private string _Status;
		
		private string _BillAsClientName;
		
		private System.Nullable<int> _ImportClientSplitMode;
		
		private string _DueText;
		
		private System.Nullable<int> _BillingGroup;
		
		private string _BillingNotes;
		
		private System.Nullable<bool> _AuditInvoices;
		
		private string _Notes;
		
		private string _PackageName;
		
		private System.Nullable<decimal> _PackageCommissionRate;
		
		private string _ClientID;
		
		private int _RankNumber;
		
		public S1_Commissions_ClientsSearchByClientNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentBillingClientID", DbType="Int")]
		public System.Nullable<int> ParentBillingClientID
		{
			get
			{
				return this._ParentBillingClientID;
			}
			set
			{
				if ((this._ParentBillingClientID != value))
				{
					this._ParentBillingClientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingClientID", DbType="Int NOT NULL")]
		public int BillingClientID
		{
			get
			{
				return this._BillingClientID;
			}
			set
			{
				if ((this._BillingClientID != value))
				{
					this._BillingClientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ClientName
		{
			get
			{
				return this._ClientName;
			}
			set
			{
				if ((this._ClientName != value))
				{
					this._ClientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(100)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(100)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(100)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Char(2)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="VarChar(10)")]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this._ZipCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoNotInvoice", DbType="Bit")]
		public System.Nullable<bool> DoNotInvoice
		{
			get
			{
				return this._DoNotInvoice;
			}
			set
			{
				if ((this._DoNotInvoice != value))
				{
					this._DoNotInvoice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GetsInvoiceDetail", DbType="Bit")]
		public System.Nullable<bool> GetsInvoiceDetail
		{
			get
			{
				return this._GetsInvoiceDetail;
			}
			set
			{
				if ((this._GetsInvoiceDetail != value))
				{
					this._GetsInvoiceDetail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillAsClientName", DbType="VarChar(100)")]
		public string BillAsClientName
		{
			get
			{
				return this._BillAsClientName;
			}
			set
			{
				if ((this._BillAsClientName != value))
				{
					this._BillAsClientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportClientSplitMode", DbType="Int")]
		public System.Nullable<int> ImportClientSplitMode
		{
			get
			{
				return this._ImportClientSplitMode;
			}
			set
			{
				if ((this._ImportClientSplitMode != value))
				{
					this._ImportClientSplitMode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueText", DbType="VarChar(50)")]
		public string DueText
		{
			get
			{
				return this._DueText;
			}
			set
			{
				if ((this._DueText != value))
				{
					this._DueText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingGroup", DbType="Int")]
		public System.Nullable<int> BillingGroup
		{
			get
			{
				return this._BillingGroup;
			}
			set
			{
				if ((this._BillingGroup != value))
				{
					this._BillingGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingNotes", DbType="VarChar(MAX)")]
		public string BillingNotes
		{
			get
			{
				return this._BillingNotes;
			}
			set
			{
				if ((this._BillingNotes != value))
				{
					this._BillingNotes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuditInvoices", DbType="Bit")]
		public System.Nullable<bool> AuditInvoices
		{
			get
			{
				return this._AuditInvoices;
			}
			set
			{
				if ((this._AuditInvoices != value))
				{
					this._AuditInvoices = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="VarChar(MAX)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this._Notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageName", DbType="VarChar(MAX)")]
		public string PackageName
		{
			get
			{
				return this._PackageName;
			}
			set
			{
				if ((this._PackageName != value))
				{
					this._PackageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackageCommissionRate", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> PackageCommissionRate
		{
			get
			{
				return this._PackageCommissionRate;
			}
			set
			{
				if ((this._PackageCommissionRate != value))
				{
					this._PackageCommissionRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="VarChar(50)")]
		public string ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this._ClientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RankNumber", DbType="Int NOT NULL")]
		public int RankNumber
		{
			get
			{
				return this._RankNumber;
			}
			set
			{
				if ((this._RankNumber != value))
				{
					this._RankNumber = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
