#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreeningONE.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="screeningONE")]
	public partial class ProductsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ProductsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ScreeningONEConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_Products_GetProductList")]
		public ISingleResult<S1_Products_GetProductListResult> S1_Products_GetProductList()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<S1_Products_GetProductListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_Products_GetProductListFromClientAndVendor")]
		public ISingleResult<S1_Products_GetProductListFromClientAndVendorResult> S1_Products_GetProductListFromClientAndVendor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientID", DbType="Int")] System.Nullable<int> clientID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VendorID", DbType="Int")] System.Nullable<int> vendorID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clientID, vendorID);
			return ((ISingleResult<S1_Products_GetProductListFromClientAndVendorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_Products_GetProductListFromVendor")]
		public ISingleResult<S1_Products_GetProductListFromVendorResult> S1_Products_GetProductListFromVendor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VendorID", DbType="Int")] System.Nullable<int> vendorID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), vendorID);
			return ((ISingleResult<S1_Products_GetProductListFromVendorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_Products_GetProductListFromClient")]
		public ISingleResult<S1_Products_GetProductListFromClientResult> S1_Products_GetProductListFromClient([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientID", DbType="Int")] System.Nullable<int> clientID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clientID);
			return ((ISingleResult<S1_Products_GetProductListFromClientResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_Products_UpdateClientProductsInfo")]
		public int S1_Products_UpdateClientProductsInfo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientProductsID", DbType="Int")] System.Nullable<int> clientProductsID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesPrice", DbType="Money")] System.Nullable<decimal> salesPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IncludeOnInvoice", DbType="Int")] System.Nullable<int> includeOnInvoice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ImportsAtBaseOrSales", DbType="Bit")] System.Nullable<bool> importsAtBaseOrSales)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clientProductsID, salesPrice, includeOnInvoice, importsAtBaseOrSales);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_Products_InsertClientProduct")]
		public int S1_Products_InsertClientProduct([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> clientid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> productid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> vendorid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clientid, productid, vendorid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S1_Products_AddProduct")]
		public ISingleResult<S1_Products_AddProductResult> S1_Products_AddProduct([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductCode", DbType="VarChar(50)")] string productCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductName", DbType="VarChar(255)")] string productName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BaseCost", DbType="Money")] System.Nullable<decimal> baseCost, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BaseCommission", DbType="Money")] System.Nullable<decimal> baseCommission, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IncludeOnInvoice", DbType="TinyInt")] System.Nullable<byte> includeOnInvoice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Employment", DbType="SmallMoney")] System.Nullable<decimal> employment, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tenant", DbType="SmallMoney")] System.Nullable<decimal> tenant, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Business", DbType="SmallMoney")] System.Nullable<decimal> business, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Volunteer", DbType="SmallMoney")] System.Nullable<decimal> volunteer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Other", DbType="SmallMoney")] System.Nullable<decimal> other)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productCode, productName, baseCost, baseCommission, includeOnInvoice, employment, tenant, business, volunteer, other);
			return ((ISingleResult<S1_Products_AddProductResult>)(result.ReturnValue));
		}
	}
	
	public partial class S1_Products_GetProductListResult
	{
		
		private int _ProductID;
		
		private string _ProductName;
		
		private string _ProductCode;
		
		private System.Nullable<decimal> _BaseCost;
		
		private System.Nullable<decimal> _BaseCommission;
		
		private byte _IncludeOnInvoice;
		
		private System.Nullable<decimal> _Employment;
		
		private System.Nullable<decimal> _Business;
		
		private System.Nullable<decimal> _Tenant;
		
		private System.Nullable<decimal> _Volunteer;
		
		private System.Nullable<decimal> _Other;
		
		public S1_Products_GetProductListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL")]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this._ProductID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this._ProductCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseCost", DbType="Money")]
		public System.Nullable<decimal> BaseCost
		{
			get
			{
				return this._BaseCost;
			}
			set
			{
				if ((this._BaseCost != value))
				{
					this._BaseCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseCommission", DbType="Money")]
		public System.Nullable<decimal> BaseCommission
		{
			get
			{
				return this._BaseCommission;
			}
			set
			{
				if ((this._BaseCommission != value))
				{
					this._BaseCommission = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncludeOnInvoice", DbType="TinyInt NOT NULL")]
		public byte IncludeOnInvoice
		{
			get
			{
				return this._IncludeOnInvoice;
			}
			set
			{
				if ((this._IncludeOnInvoice != value))
				{
					this._IncludeOnInvoice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employment", DbType="SmallMoney")]
		public System.Nullable<decimal> Employment
		{
			get
			{
				return this._Employment;
			}
			set
			{
				if ((this._Employment != value))
				{
					this._Employment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Business", DbType="SmallMoney")]
		public System.Nullable<decimal> Business
		{
			get
			{
				return this._Business;
			}
			set
			{
				if ((this._Business != value))
				{
					this._Business = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenant", DbType="SmallMoney")]
		public System.Nullable<decimal> Tenant
		{
			get
			{
				return this._Tenant;
			}
			set
			{
				if ((this._Tenant != value))
				{
					this._Tenant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volunteer", DbType="SmallMoney")]
		public System.Nullable<decimal> Volunteer
		{
			get
			{
				return this._Volunteer;
			}
			set
			{
				if ((this._Volunteer != value))
				{
					this._Volunteer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other", DbType="SmallMoney")]
		public System.Nullable<decimal> Other
		{
			get
			{
				return this._Other;
			}
			set
			{
				if ((this._Other != value))
				{
					this._Other = value;
				}
			}
		}
	}
	
	public partial class S1_Products_GetProductListFromClientAndVendorResult
	{
		
		private int _ProductID;
		
		private string _ProductCode;
		
		private string _ProductName;
		
		private System.Nullable<decimal> _BaseCost;
		
		private System.Nullable<decimal> _BaseCommission;
		
		private byte _IncludeOnInvoice;
		
		private System.Nullable<decimal> _Employment;
		
		private System.Nullable<decimal> _Tenant;
		
		private System.Nullable<decimal> _Business;
		
		private System.Nullable<decimal> _Volunteer;
		
		private System.Nullable<decimal> _Other;
		
		public S1_Products_GetProductListFromClientAndVendorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL")]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this._ProductID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this._ProductCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseCost", DbType="Money")]
		public System.Nullable<decimal> BaseCost
		{
			get
			{
				return this._BaseCost;
			}
			set
			{
				if ((this._BaseCost != value))
				{
					this._BaseCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseCommission", DbType="Money")]
		public System.Nullable<decimal> BaseCommission
		{
			get
			{
				return this._BaseCommission;
			}
			set
			{
				if ((this._BaseCommission != value))
				{
					this._BaseCommission = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncludeOnInvoice", DbType="TinyInt NOT NULL")]
		public byte IncludeOnInvoice
		{
			get
			{
				return this._IncludeOnInvoice;
			}
			set
			{
				if ((this._IncludeOnInvoice != value))
				{
					this._IncludeOnInvoice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employment", DbType="SmallMoney")]
		public System.Nullable<decimal> Employment
		{
			get
			{
				return this._Employment;
			}
			set
			{
				if ((this._Employment != value))
				{
					this._Employment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenant", DbType="SmallMoney")]
		public System.Nullable<decimal> Tenant
		{
			get
			{
				return this._Tenant;
			}
			set
			{
				if ((this._Tenant != value))
				{
					this._Tenant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Business", DbType="SmallMoney")]
		public System.Nullable<decimal> Business
		{
			get
			{
				return this._Business;
			}
			set
			{
				if ((this._Business != value))
				{
					this._Business = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volunteer", DbType="SmallMoney")]
		public System.Nullable<decimal> Volunteer
		{
			get
			{
				return this._Volunteer;
			}
			set
			{
				if ((this._Volunteer != value))
				{
					this._Volunteer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other", DbType="SmallMoney")]
		public System.Nullable<decimal> Other
		{
			get
			{
				return this._Other;
			}
			set
			{
				if ((this._Other != value))
				{
					this._Other = value;
				}
			}
		}
	}
	
	public partial class S1_Products_GetProductListFromVendorResult
	{
		
		private int _ProductID;
		
		private string _ProductName;
		
		public S1_Products_GetProductListFromVendorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL")]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this._ProductID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(306) NOT NULL", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
	}
	
	public partial class S1_Products_GetProductListFromClientResult
	{
		
		private int _ClientProductsID;
		
		private string _ProductCode;
		
		private string _ProductName;
		
		private System.Nullable<decimal> _BaseCost;
		
		private System.Nullable<decimal> _BaseCommission;
		
		private byte _IncludeOnInvoice;
		
		private System.Nullable<decimal> _Employment;
		
		private System.Nullable<decimal> _Tenant;
		
		private System.Nullable<decimal> _Business;
		
		private System.Nullable<decimal> _Volunteer;
		
		private System.Nullable<decimal> _Other;
		
		private string _VendorName;
		
		private int _ImportsAtBaseOrSales;
		
		private System.Nullable<decimal> _SalesPrice;
		
		private int _VendorID;
		
		public S1_Products_GetProductListFromClientResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientProductsID", DbType="Int NOT NULL")]
		public int ClientProductsID
		{
			get
			{
				return this._ClientProductsID;
			}
			set
			{
				if ((this._ClientProductsID != value))
				{
					this._ClientProductsID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this._ProductCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseCost", DbType="Money")]
		public System.Nullable<decimal> BaseCost
		{
			get
			{
				return this._BaseCost;
			}
			set
			{
				if ((this._BaseCost != value))
				{
					this._BaseCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseCommission", DbType="Money")]
		public System.Nullable<decimal> BaseCommission
		{
			get
			{
				return this._BaseCommission;
			}
			set
			{
				if ((this._BaseCommission != value))
				{
					this._BaseCommission = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncludeOnInvoice", DbType="TinyInt NOT NULL")]
		public byte IncludeOnInvoice
		{
			get
			{
				return this._IncludeOnInvoice;
			}
			set
			{
				if ((this._IncludeOnInvoice != value))
				{
					this._IncludeOnInvoice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employment", DbType="SmallMoney")]
		public System.Nullable<decimal> Employment
		{
			get
			{
				return this._Employment;
			}
			set
			{
				if ((this._Employment != value))
				{
					this._Employment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenant", DbType="SmallMoney")]
		public System.Nullable<decimal> Tenant
		{
			get
			{
				return this._Tenant;
			}
			set
			{
				if ((this._Tenant != value))
				{
					this._Tenant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Business", DbType="SmallMoney")]
		public System.Nullable<decimal> Business
		{
			get
			{
				return this._Business;
			}
			set
			{
				if ((this._Business != value))
				{
					this._Business = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volunteer", DbType="SmallMoney")]
		public System.Nullable<decimal> Volunteer
		{
			get
			{
				return this._Volunteer;
			}
			set
			{
				if ((this._Volunteer != value))
				{
					this._Volunteer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other", DbType="SmallMoney")]
		public System.Nullable<decimal> Other
		{
			get
			{
				return this._Other;
			}
			set
			{
				if ((this._Other != value))
				{
					this._Other = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorName", DbType="VarChar(100)")]
		public string VendorName
		{
			get
			{
				return this._VendorName;
			}
			set
			{
				if ((this._VendorName != value))
				{
					this._VendorName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportsAtBaseOrSales", DbType="Int NOT NULL")]
		public int ImportsAtBaseOrSales
		{
			get
			{
				return this._ImportsAtBaseOrSales;
			}
			set
			{
				if ((this._ImportsAtBaseOrSales != value))
				{
					this._ImportsAtBaseOrSales = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesPrice", DbType="Money")]
		public System.Nullable<decimal> SalesPrice
		{
			get
			{
				return this._SalesPrice;
			}
			set
			{
				if ((this._SalesPrice != value))
				{
					this._SalesPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorID", DbType="Int NOT NULL")]
		public int VendorID
		{
			get
			{
				return this._VendorID;
			}
			set
			{
				if ((this._VendorID != value))
				{
					this._VendorID = value;
				}
			}
		}
	}
	
	public partial class S1_Products_AddProductResult
	{
		
		private System.Nullable<int> _productID;
		
		public S1_Products_AddProductResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productID", DbType="Int")]
		public System.Nullable<int> productID
		{
			get
			{
				return this._productID;
			}
			set
			{
				if ((this._productID != value))
				{
					this._productID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
