<?xml version="1.0" encoding="utf-8"?><Database Name="screeningONE" Class="VendorsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress2016;Initial Catalog=WesternReportingLocal;Persist Security Info=True;User ID=screeningONE_DevUser" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ScreeningONEConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.S1_Vendors_GetVendorList" Method="S1_Vendors_GetVendorList">
    <ElementType Name="S1_Vendors_GetVendorListResult">
      <Column Name="VendorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VendorName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.S1_Vendors_AddProductToVendor" Method="S1_Vendors_AddProductToVendor">
    <Parameter Name="vendorID" Type="System.Int32" DbType="Int" />
    <Parameter Name="productID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>